default_language_version:
  python: python3.7

repos:
  - repo: local
    hooks:
      - id: isort
        name: isort
        stages: [commit]
        language: system
        entry: isort pp.py
        types: [python]

      - id: black
        name: black
        stages: [commit]
        language: system
        entry: black pp.py
        types: [python]

      - id: flake8
        name: flake8
        stages: [commit]
        language: system
        entry: flake8 pp.py
        types: [python]
        exclude: setup.cfg

      - id: pytest
        name: pytest
        pass_filenames: false
        stages: [commit]
        language: system
        entry: pytest --capture=tee-sys
        types: [python]
