default_language_version:
  python: python3.7

repos:
  - repo: local
    hooks:
      - id: isort
        name: isort
        stages: [commit]
        language: system
        entry: source env/bin/activate; isort pp.py; deactivate
        types: [python]

      - id: black
        name: black
        stages: [commit]
        language: system
        entry: source env/bin/activate; black pp.py; deactivate
        types: [python]
